# Generated by Django 3.2.16 on 2023-11-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
